name: docker-alpine-epusdt
on:
  workflow_dispatch: #github页面手动触发
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: epusdt #这是您的镜像名

jobs:        
  push-docker-hub:    
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_alpine
          push: true
          tags: |            
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:alpine
